version: '3'
services:

  redis:
    image: redis:6.2-alpine

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=$FFXG_DB
      - DB_USER=$FFXG_USER
    volumes:
      - /var/run/mysqld/:/var/run/mysqld/
      - ./:/ffxg/
      - ./instances/$FFXG_DB/dbpassword/:/dbpassword/
    depends_on:
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    volumes:
      - /var/run/mysqld/:/var/run/mysqld/
      - ./:/ffxg/
      - ./instances/$FFXG_DB/dbpassword/:/dbpassword/
    command: "./docker/entrypoint-sidekiq.sh"
